server:
  port: 3333

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:11521:xe
    username: system
    password: mybtc
    driver-class-name: oracle.jdbc.OracleDriver


mybatis:
  type-aliases-package: com.rest.api.VO
  mapper-locations: classspath:mapper/*.xml