server:
  port: 8083

spring:
  mail:
    host: smtp.naver.com
    port: 465
    username: insfo_sample@naver.com
    password: sechacking123
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.0.1.100:11521/xe
    username: mybtc
    password: mybtc
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  jmx:
    enabled: false
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    redis:
      namespace: spring:session

mybatis:
  type-aliases-package: com.rest.api.VO
  mapper-locations: classspath:mapper/*.xml